### ISSUE TITLE
RMSE calculation

### ISSUE THREAD

**Issue by lee1043** [NCAR/CVDP-ncl#8]
Thanks @phillips-ad for your quick response. Here I open an issue for future communications, and attached part of my previous email below.

-----
On Thu, Aug 29, 2019 at 10:18 AM:

... we noted a large discrepancy in the case of the RMSE.

When I was investigating the cause of the discrepancy for RMSE (please see 2nd page of attached PDF, on left panel), I noticed that in the CVDP the area-weighting for RMSE calculation is applied prior to squaring the difference between the model and the observations. In this case the sum of the area weights (at a given longitude) < 2. In the PCMDI modes tool the area-weight is applied to difference-squared, as seen in formula on the right panel of slide 2. In this case, as expected, the sum of the area-weight = 2 at a given longitude. As such, the discrepancy in the two formulae result in the CVDP having consistently lower RMSE compared to the PMP (plot in the left panel of the slide). By moving the area-weight outside of the parentheses in a local copy of the CVDP code, consistent results between the CVDP and the PMP as seen in the plot in the right panel of slide 2.

To be certain of the suggested change, I’ve tested those two formulae by applying them to generated test fields (please see the 3rd page of the PDF). The difference between field A and B is exactly 2 at every grid point, which means RMSE between those two fields should be equal to 2, regardless of the considered domain. As originally coded in the CVDP the RMSE is << 2, while with the revised formula the RMSE is exactly 2, as expected.

I propose revising the current code (written in the way of in the yellow box of 3rd page of the PDF) to the way in the green box, to ensure getting the correct area-weighted RMSE. A search of the ncl repository suggests that this change needs to be made for numerous .ncl scripts, as it appears that a chunks of code were copied for the calculation of different modes.

...

**Comment by phillips-ad** [comment]
@lee1043 thanks so much for the clear description and solution to the issue you identified. I have verified the issue, and will be releasing CVDP v5.1.1 within the next two weeks with a fix to the RMSE calculation. Thanks again for the time that you took in documenting the issue.

**Comment by lee1043** [comment]
@phillips-ad Excellent, thanks for following up!
